# Generated by Django 4.2.20 on 2025-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Ph.D', 'Ph.D')], default='B.Tech', max_length=6)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('content', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students_photos/')),
            ],
        ),
    ]
