# Generated by Django 4.2.20 on 2025-05-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
