# Generated by Django 4.2.20 on 2025-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_awards_student_other_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='research',
            field=models.TextField(blank=True, null=True),
        ),
    ]
