# Generated by Django 4.2.20 on 2025-05-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link', models.URLField(help_text='Link to external news or full article')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
