# Generated by Django 4.2.20 on 2025-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='newsitem',
            old_name='summary',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='title',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='headline',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
