# Generated by Django 4.2.20 on 2025-05-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_rename_summary_newsitem_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='published_date',
        ),
    ]
