# Generated by Django 3.1.14 on 2025-06-13 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20250608_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
