# Generated by Django 4.2.20 on 2025-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='affiliated_centres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='profile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='teaching_interests',
            field=models.TextField(blank=True),
        ),
    ]
