# Generated by Django 4.2.20 on 2025-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultymember_affiliated_centres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('slug', models.SlugField(unique=True)),
                ('phd_details', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('web_profile', models.URLField(blank=True, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('affiliations', models.ManyToManyField(blank=True, to='faculty.affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyMember',
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_interests',
            field=models.ManyToManyField(blank=True, to='faculty.researchinterest'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teaching_interests',
            field=models.ManyToManyField(blank=True, to='faculty.teachinginterest'),
        ),
    ]
