# Generated by Django 4.2.20 on 2025-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_affiliation_faculty_researchinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='slug',
            field=models.SlugField(default='default-slug', unique=False, blank=True),
        ),
    ]
