# Generated by Django 4.2.20 on 2025-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_affiliation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug'),
        ),
    ]
