# Generated by Django 3.1.14 on 2025-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default='\\static\x07ssets\\Amit_Kumar_Ratrey.jpg', upload_to='students_photos/'),
        ),
    ]
