# Generated by Django 3.1.14 on 2025-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('phd', 'PhD'), ('mtech', 'MTech'), ('btech', 'BTech'), ('alumni', 'Alumni')], max_length=10)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('current_affiliation', models.CharField(blank=True, max_length=200)),
                ('profile_photo', models.ImageField(blank=True, upload_to='team_photos/')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
