# Generated by Django 3.1.14 on 2025-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250313_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
