# Generated by Django 3.1.14 on 2025-03-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250313_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='post',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
