# Generated by Django 3.1.14 on 2025-06-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
