# Generated by Django 3.1.14 on 2025-06-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
