# Generated by Django 3.1.14 on 2025-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20250608_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionvision',
            name='title',
            field=models.CharField(default='Mission & Vision', max_length=200),
        ),
    ]
